---
- hosts : localhost
  connection : local
  tasks :
    - docker_cotainer :
        name : myhello
        image : momoclass5/myhello:latest
        state: started
        ports :
          - "80:8080"
...
